export const words={
    eng:{
        home:"Home",
        login:"Login",
        orders:"Orders",
        logout:"Logout",
    },
    ar:{
        home:"البيت",
        login:"دخول",
        orders:"طلبات",
        logout:"خروج",
    },
    heb:{
        home:"הבית",
        login:"כניסה",
        orders:"בקשות",
        logout:"יציאה",
    }
}